dict= {
    "Ephemeral": "थोड़े समय का",
"Ubiquitous": "हर जगह",
"Mellifluous": "मीठा",
"Ineffable": "जो कहा न जा सके",
"Serendipity": "अचानक मिलना",
"Pernicious": "हानिकारक",
"Obfuscate": "उलझाना",
"Capricious": "मनमौजी",
"Esoteric": "गुप्त",
"Plethora": "बहुत अधिक",
"Taciturn": "कम बोलने वाला",
"Vicissitude": "बदलाव",
"Magnanimous": "बड़ा दिल वाला",
"Incipient": "शुरूआती",
"Redundant": "बेकार",
"Conundrum": "मुश्किल सवाल",
"Gregarious": "मिलनसार",
"Disparate": "अलग-अलग",
"Ambivalent": "दुविधा में",
"Quixotic": "असंभव",
"Tenacious": "मजबूत",
"Veracity": "सच्चाई",
"Alacrity": "जल्दी",
"Superfluous": "अतिरिक्त",
"Enigma": "पहेली",
"Fortuitous": "अचानक हुआ",
"Immutable": "न बदलने वाला",
"Resilient": "लचीला",
"Clandestine": "छुपकर",
"Prodigious": "बहुत बड़ा",
"Aptitude": "काबिलियत",
"Conjecture": "अंदाज़ा",
"Dilemma": "समस्या",
"Exacerbate": "बढ़ाना",
"Frugal": "किफायती",
"Hinder": "रोकना",
"Impetuous": "बिना सोचे",
"Judicious": "समझदारी वाला",
"Lethargic": "आलसी",
"Meticulous": "बारीक काम करने वाला",
"Novel": "नया",
"Ominous": "बुरा संकेत",
"Paradox": "उल्टा लगना",
"Reticent": "चुप रहने वाला",
"Scrupulous": "ईमानदार",
"Transient": "थोड़े समय के लिए",
"Vacillate": "हिचकिचाना",
"Wary": "सावधान",
"Zealous": "उत्साही",
"Axiomatic": "सच माना हुआ",
"Absence": "अनुपस्थिति",
"Accept": "स्वीकार करना",
"Accident": "दुर्घटना",
"Account": "खाता",
"Achieve": "प्राप्त करना",
"Action": "क्रिया",
"Address": "पता",
"Adult": "वयस्क",
"Advice": "सलाह",
"Affect": "प्रभावित करना",
"Again": "फिर से",
"Agree": "सहमत होना",
"Almost": "लगभग",
"Always": "हमेशा",
"Amount": "मात्रा",
"Animal": "जानवर",
"Answer": "उत्तर",
"Appear": "दिखाई देना",
"Area": "क्षेत्र",
"Around": "आसपास",
"Arrival": "आगमन",
"Article": "लेख",
"Artist": "कलाकार",
"Ask": "पूछना",
"Attack": "हमला",
"Attempt": "प्रयास",
"Attend": "उपस्थित होना",
"Attention": "ध्यान",
"Authority": "अधिकार",
"Available": "उपलब्ध",
"Average": "औसत",
"Avoid": "बचना",
"Aware": "जागरूक",
"Back": "पीछे",
"Balance": "संतुलन",
"Base": "आधार",
"Basic": "मूलभूत",
"Become": "बनना",
"Begin": "शुरू करना",
"Behind": "पीछे",
"Believe": "विश्वास करना",
"Below": "नीचे",
"Besides": "अलावा",
"Between": "बीच में",
"Beyond": "परे",
"Bill": "बिल",
"Board": "बोर्ड",
"Body": "शरीर",
"Bottom": "नीचे का भाग",
"Branch": "शाखा",
"Break": "तोड़ना",
"Bring": "लाना",
"Build": "बनाना",
"Business": "व्यापार",
"Calculate": "गणना करना",
"Call": "बुलाना",
"Campaign": "अभियान",
"Capacity": "क्षमता",
"Carry": "ले जाना",
"Cause": "कारण",
"Certain": "निश्चित",
"Change": "बदलना",
"Chapter": "अध्याय",
"Character": "चरित्र",
"Check": "जांचना",
"Choice": "चुनाव",
"Claim": "दावा",
"Clear": "साफ",
"Client": "ग्राहक",
"Close": "बंद करना",
"Collect": "इकट्ठा करना",
"College": "कॉलेज",
"Combine": "मिलाना",
"Command": "आदेश",
"Comment": "टिप्पणी",
"Commit": "वचन देना",
"Common": "सामान्य",
"Community": "समुदाय",
"Compare": "तुलना करना",
"Complete": "पूरा करना",
"Concern": "चिंता",
"Conduct": "संचालन करना",
"Confirm": "पुष्टि करना",
"Connect": "जोड़ना",
"Consider": "विचार करना",
"Consist": "शामिल होना",
"Constant": "लगातार",
"Construct": "निर्माण करना",
"Contact": "संपर्क",
"Contain": "शामिल करना",
"Continue": "जारी रखना",
"Contract": "अनुबंध",
"Control": "नियंत्रण",
"Convert": "परिवर्तित करना",
"Copy": "प्रतिलिपि",
"Correct": "सही",
"Cost": "कीमत",
"Could": "सकता था",
"Count": "गिनना",
"Country": "देश",
"Apple": "सेब",
"Book": "किताब",
"Car": "गाड़ी",
"Day": "दिन",
"Eat": "खाना",
"Friend": "दोस्त",
"Go": "जाना",
"House": "घर",
"Important": "ज़रूरी",
"Job": "नौकरी",
"Kind": "दयालु",
"Love": "प्यार",
"Money": "पैसा",
"Name": "नाम",
"Open": "खोलना",
"People": "लोग",
"Question": "सवाल",
"Run": "दौड़ना",
"See": "देखना",
"Time": "समय",
"Understand": "समझना",
"Very": "बहुत",
"Water": "पानी",
"Yes": "हाँ",
"Zero": "शून्य",
"Ability": "क्षमता",
"Beautiful": "सुंदर",
"Care": "ध्यान",
"Different": "अलग",
"Easy": "आसान",
"Family": "परिवार",
"Give": "देना",
"Happy": "खुश",
"Idea": "विचार",
"Keep": "रखना",
"Learn": "सीखना",
"Music": "संगीत",
"Need": "ज़रूरत",
"Often": "अक्सर",
"Problem": "समस्या",
"Quiet": "शांत",
"Reason": "कारण",
"Start": "शुरू करना",
"Think": "सोचना",
"Use": "इस्तेमाल करना",
"Walk": "चलना",
"Year": "साल",
"Zone": "क्षेत्र",
"Accurate": "सटीक",
"Benefit": "फ़ायदा",
"Challenge": "चुनौती",
"Develop": "विकसित करना",
"Effect": "प्रभाव",
"Famous": "प्रसिद्ध",
"Gather": "इकट्ठा करना",
"Honest": "ईमानदार",
"Imagine": "कल्पना करना",
"Journey": "यात्रा",
"Knowledge": "ज्ञान",
"Limit": "सीमा",
"Manage": "प्रबंध करना",
"Notice": "ध्यान देना",
"Opportunity": "अवसर",
"Prepare": "तैयार करना",
"Require": "आवश्यकता",
"Support": "समर्थन",
"Translate": "अनुवाद करना",
"Value": "मूल्य",
"Witness": "गवाह",
"Yield": "उपज",
"Abundant": "प्रचुर",
"Brave": "बहादुर",
"Comprehend": "समझना",
"Durable": "टिकाऊ",
"Elegant": "सुंदर",
"Flexible": "लचीला",
"Genuine": "असली",
"Harmonious": "सामंजस्यपूर्ण",
"Illuminate": "प्रकाशित करना",
"Justify": "उचित ठहराना",
"Luminous": "चमकदार",
"Moderate": "मध्यम",
"Nurture": "पालन करना",
"Observe": "निरीक्षण करना",
"Patience": "धैर्य",
"Rational": "तर्कसंगत",
"Satisfy": "संतुष्ट करना",
"Tolerate": "सहन करना",
"Unique": "अद्वितीय",
"Vibrant": "जीवंत",
"Wholesome": "पौष्टिक",
"Xenodochial": "मेहमान नवाज",
"Yearn": "तरसना",
"Zenith": "चरम सीमा",
"Abhor": "घृणा करना",
"Benevolent": "परोपकारी",
"Consolidate":"मजबूत करना",
"Detrimental": "हानिकारक",
"Elucidate":"स्पष्ट करना",
"Facilitate": "सुगम बनाना",
"Course": "पाठ्यक्रम",
"Cover": "ढकना",
"Create": "बनाना",
"Credit": "श्रेय",
"Crime": "अपराध",
"Critical": "महत्वपूर्ण",
"Culture": "संस्कृति",
"Current": "वर्तमान",
"Customer": "ग्राहक",
"Damage": "नुकसान",
"Danger": "खतरा",
"Dark": "अंधेरा",
"Data": "आंकड़े",
"Deal": "सौदा",
"Death": "मृत्यु",
"Debate": "बहस",
"Decide": "तय करना",
"Deep": "गहरा",
"Define": "परिभाषित करना",
"Degree": "डिग्री",
"Deliver": "पहुंचाना",
"Demand": "मांग",
"Depart": "रवाना होना",
"Depend": "निर्भर होना",
"Describe": "वर्णन करना",
"Design": "डिज़ाइन",
"Detail": "विवरण",
"Determine": "निर्धारित करना",
"Develop": "विकसित करना",
"Device": "उपकरण",
"Dialogue": "संवाद",
"Die": "मरना",
"Difference": "अंतर",
"Direct": "सीधा",
"Direction": "दिशा",
"Discover": "खोज करना",
"Discuss": "चर्चा करना",
"Distance": "दूरी",
"Divide": "विभाजित करना",
"Document": "दस्तावेज़",
"Double": "दोगुना",
"Down": "नीचे",
"Draw": "खींचना",
"Drive": "गाड़ी चलाना",
"During": "दौरान",
"Each": "प्रत्येक",
"Early": "जल्दी",
"Earn": "कमाना",
"Earth": "पृथ्वी",
"Economic": "आर्थिक",
"Edge": "किनारा",
"Educate": "शिक्षित करना",
"Effort": "प्रयास",
"Either": "या",
"Elect": "चुनना",
"Element": "तत्व",
"Emergency": "आपातकाल",
"Emotion": "भावना",
"Employ": "नियुक्त करना",
"Enable": "सक्षम करना",
"Encounter": "सामना करना",
"Energy": "ऊर्जा",
"Engage": "शामिल होना",
"Engine": "इंजन",
"Enjoy": "आनंद लेना",
"Enough": "पर्याप्त",
"Enter": "प्रवेश करना",
"Entire": "पूरा",
"Environment": "पर्यावरण",
"Equal": "बराबर",
"Equipment": "उपकरण",
"Error": "गलती",
"Establish": "स्थापित करना",
"Estimate": "अनुमान लगाना",
"Evaluate": "मूल्यांकन करना",
"Event": "घटना",
"Eventually": "अंततः",
"Evidence": "सबूत",
"Exact": "सटीक",
"Example": "उदाहरण",
"Exchange": "आदान-प्रदान",
"Exercise": "व्यायाम",
"Exhibit": "प्रदर्शित करना",
"Exist": "अस्तित्व में होना",
"Expect": "उम्मीद करना",
"Experience": "अनुभव",
"Explain": "समझाना",
"Explore": "खोज करना",
"Express": "व्यक्त करना",
"Extend": "विस्तार करना",
"External": "बाहरी",
"Extra": "अतिरिक्त",
"Face": "चेहरा",
"Factor": "कारक",
"Fail": "असफल होना",
"Fair": "उचित",
"Fall": "गिरना",
"Fast": "तेज़",
"Feature": "विशेषता",
"Federal": "संघीय",
"Field": "क्षेत्र",
"Figure": "आंकड़ा",
"File": "फ़ाइल",
"Film": "फ़िल्म",
"Final": "अंतिम",
"Finance": "वित्त",
"Find": "ढूंढना",
"Fine": "ठीक",
"Finish": "समाप्त करना",
"Firm": "फर्म",
"First": "पहला",
"Fit": "फिट",
"Fix": "ठीक करना",
"Flight": "उड़ान",
"Focus": "ध्यान केंद्रित करना",
"Follow": "अनुसरण करना",
"Force": "बल",
"Foreign": "विदेशी",
"Forget": "भूलना",
"Form": "रूप",
"Former": "पूर्व",
"Forward": "आगे",
"Found": "स्थापित करना",
"Frame": "फ्रेम",
"Free": "मुक्त",
"Frequency": "आवृत्ति",
"Fresh": "ताजा",
"Front": "सामने",
"Function": "कार्य",
"Fund": "निधि",
"Future": "भविष्य",
"Gain": "लाभ",
"Game": "खेल",
"General": "सामान्य",
"Generate": "उत्पन्न करना",
"Goal": "लक्ष्य",
"Good": "अच्छा",
"Govern": "शासन करना",
"Grade": "ग्रेड",
"Grant": "अनुदान",
"Great": "महान",
"Green": "हरा",
"Ground": "जमीन",
"Group": "समूह",
"Grow": "बढ़ना",
"Guarantee": "गारंटी",
"Guide": "मार्गदर्शन करना",
"Half": "आधा",
"Handle": "संभालना",
"Happen": "होना",
"Hard": "कठिन",
"Head": "सिर",
"Health": "स्वास्थ्य",
"Hear": "सुनना",
"Heart": "दिल",
"Heat": "गर्मी",
"Heavy": "भारी",
"Help": "मदद करना",
"Here": "यहां",
"High": "उच्च",
"History": "इतिहास",
"Hold": "पकड़ना",
"Hope": "आशा",
"Hotel": "होटल",
"Hour": "घंटा",
"However": "हालांकि",
"Huge": "विशाल",
"Human": "मानव",
"Hundred": "सौ",
"Impact": "प्रभाव",
"Implement": "कार्यान्वित करना",
"Improve": "सुधार करना",
"Include": "शामिल करना",
"Income": "आय",
"Increase": "बढ़ाना",
"Indeed": "वास्तव में",
"Indicate": "संकेत देना",
"Individual": "व्यक्तिगत",
"Industry": "उद्योग",
"Influence": "प्रभाव",
"Inform": "सूचित करना",
"Inside": "अंदर",
"Instead": "बजाय",
"Institute": "संस्थान",
"Insurance": "बीमा",
"Intend": "इरादा रखना",
"Interest": "रुचि",
"Internal": "आंतरिक",
"Introduce": "परिचय कराना",
"Invest": "निवेश करना",
"Involve": "शामिल करना",
"Issue": "मुद्दा",
"Item": "वस्तु",
"Join": "शामिल होना",
"Judge": "न्याय करना",
"Just": "सिर्फ",
"Key": "चाबी",
"Kill": "मारना",
"Kind": "प्रकार",
"King": "राजा",
"Kitchen": "रसोई",
"Know": "जानना",
"Label": "लेबल",
"Land": "भूमि",
"Language": "भाषा",
"Large": "बड़ा",
"Last": "अंतिम",
"Late": "देर",
"Law": "कानून",
"Lay": "रखना",
"Lead": "नेतृत्व करना",
"Learn": "सीखना",
"Least": "कम से कम",
"Leave": "छोड़ना",
"Left": "बाएं",
"Leg": "पैर",
"Legal": "कानूनी",
"Level": "स्तर",
"Lie": "झूठ बोलना",
"Life": "जीवन",
"Light": "रोशनी",
"Like": "पसंद करना",
"Line": "पंक्ति",
"List": "सूची",
"Listen": "सुनना",
"Little": "थोड़ा",
"Live": "रहना",
"Load": "भार",
"Local": "स्थानीय",
"Locate": "पता लगाना",
"Long": "लंबा",
"Look": "देखना",
"Lose": "खोना",
"Lot": "बहुत",
"Low": "कम",
"Machine": "मशीन",
"Main": "मुख्य",
"Maintain": "बनाए रखना",
"Major": "प्रमुख",
"Make": "बनाना",
"Manage": "प्रबंध करना",
"Many": "कई",
"Mark": "चिह्न",
"Market": "बाजार",
"Mass": "द्रव्यमान",
"Match": "मिलान करना",
"Material": "सामग्री",
"Matter": "मामला",
"May": "शायद",
"Measure": "मापना",
"Media": "मीडिया",
"Medical": "चिकित्सा",
"Meet": "मिलना",
"Member": "सदस्य",
"Mention": "उल्लेख करना",
"Message": "संदेश",
"Method": "विधि",
"Middle": "मध्य",
"Might": "शायद",
"Mile": "मील",
"Military": "सैन्य",
"Mind": "मन",
"Minute": "मिनट",
"Miss": "चूकना",
"Mission": "मिशन",
"Model": "मॉडल",
"Modern": "आधुनिक",
"Moment": "क्षण",
"Month": "महीना",
"More": "अधिक",
"Morning": "सुबह",
"Most": "सबसे अधिक",
"Mother": "मां",
"Motion": "गति",
"Mount": "चढ़ना",
"Move": "चलना",
"Much": "बहुत",
"Multiple": "कई",
"Music": "संगीत",
"Must": "चाहिए",
"Mutual": "आपसी",
"Nation": "राष्ट्र",
"Natural": "प्राकृतिक",
"Near": "पास",
"Necessary": "आवश्यक",
"Network": "नेटवर्क",
"Never": "कभी नहीं",
"New": "नया",
"Next": "अगला",
"Night": "रात",
"None": "कोई नहीं",
"Normal": "सामान्य",
"Note": "नोट",
"Nothing": "कुछ नहीं",
"Number": "संख्या",
"Object": "वस्तु",
"Occur": "होना",
"Offer": "प्रस्ताव",
"Office": "कार्यालय",
"Often": "अक्सर",
"Once": "एक बार",
"Only": "केवल",
"Onto": "पर",
"Order": "आदेश",
"Ordinary": "साधारण",
"Organize": "व्यवस्थित करना",
"Original": "मूल",
"Other": "अन्य",
"Outcome": "परिणाम",
"Outside": "बाहर",
"Overall": "कुल मिलाकर",
"Owner": "मालिक",
"Page": "पृष्ठ",
"Pain": "दर्द",
"Paper": "कागज",
"Parent": "माता-पिता",
"Part": "भाग",
"Particular": "विशेष",
"Partner": "साथी",
"Party": "पार्टी",
"Pass": "गुजरना",
"Past": "अतीत",
"Patient": "रोगी",
"Pattern": "पैटर्न",
"Pay": "भुगतान करना",
"Peace": "शांति",
"Perform": "प्रदर्शन करना",
"Perhaps": "शायद",
"Period": "अवधि",
"Person": "व्यक्ति",
"Phase": "चरण",
"Phone": "फोन",
"Physical": "शारीरिक",
"Pick": "चुनना",
"Piece": "टुकड़ा",
"Place": "स्थान",
"Plan": "योजना",
"Plant": "पौधा",
"Play": "खेलना",
"Point": "बिंदु",
"Police": "पुलिस",
"Policy": "नीति",
"Political": "राजनीतिक",
"Poor": "गरीब",
"Popular": "लोकप्रिय",
"Position": "स्थिति",
"Positive": "सकारात्मक",
"Possible": "संभव",
"Power": "शक्ति",
"Practice": "अभ्यास",
"Prepare": "तैयार करना",
"Present": "वर्तमान",
"President": "राष्ट्रपति",
"Pressure": "दबाव",
"Pretty": "सुंदर",
"Prevent": "रोकना",
"Previous": "पिछला",
"Price": "कीमत",
"Private": "निजी",
"Probably": "शायद",
"Problem": "समस्या",
"Process": "प्रक्रिया",
"Produce": "उत्पादन करना",
"Product": "उत्पाद",
"Program": "कार्यक्रम",
"Project": "परियोजना",
"Property": "संपत्ति",
"Protect": "रक्षा करना",
"Prove": "साबित करना",
"Provide": "प्रदान करना",
"Public": "सार्वजनिक",
"Pull": "खींचना",
"Purpose": "उद्देश्य",
"Push": "धक्का देना",
"Quality": "गुणवत्ता",
"Quantity": "मात्रा",
"Question": "प्रश्न",
"Quick": "शीघ्र",
"Quite": "काफी",
"Range": "सीमा",
"Rate": "दर",
"Rather": "बल्कि",
"Reach": "पहुंचना",
"React": "प्रतिक्रिया करना",
"Read": "पढ़ना",
"Ready": "तैयार",
"Real": "वास्तविक",
"Realize": "एहसास होना",
"Really": "सच में",
"Reason": "कारण",
"Receive": "प्राप्त करना",
"Recent": "हाल ही का",
"Recognize": "पहचानना",
"Record": "रिकॉर्ड",
"Reduce": "कम करना",
"Refer": "संदर्भ देना",
"Reflect": "प्रतिबिंबित करना",
"Region": "क्षेत्र",
"Relate": "संबंधित होना",
"Release": "रिहा करना",
"Relevant": "प्रासंगिक",
"Remain": "रहना",
"Remember": "याद रखना",
"Remove": "हटाना",
"Report": "रिपोर्ट",
"Represent": "प्रतिनिधित्व करना",
"Require": "आवश्यकता होना",
"Research": "अनुसंधान",
"Resource": "संसाधन",
"Respond": "प्रतिक्रिया देना",
"Responsibility": "जिम्मेदारी",
"Rest": "आराम",
"Result": "परिणाम",
"Return": "वापस आना",
"Reveal": "प्रकट करना",
"Review": "समीक्षा",
"Right": "सही",
"Rise": "उठना",
"Risk": "जोखिम",
"Road": "सड़क",
"Role": "भूमिका",
"Room": "कमरा",
"Round": "गोल",
"Rule": "नियम",
"Run": "दौड़ना",
"Safe": "सुरक्षित",
"Same": "वही",
"Sample": "नमूना",
"Save": "बचाना",
"Say": "कहना",
"Scale": "पैमाना",
"Scene": "दृश्य",
"Schedule": "अनुसूची",
"Scheme": "योजना",
"School": "विद्यालय",
"Science": "विज्ञान",
"Score": "अंक",
"Screen": "स्क्रीन",
"Search": "खोज",
"Season": "मौसम",
"Second": "दूसरा",
"Section": "खंड",
"Secure": "सुरक्षित करना",
"See": "देखना",
"Seek": "खोजना",
"Seem": "लगना",
"Select": "चुनना",
"Sense": "इंद्रिय",
"Separate": "अलग करना",
"Series": "श्रृंखला",
"Serious": "गंभीर",
"Serve": "सेवा करना",
"Session": "सत्र",
"Set": "सेट",
"Settle": "निपटान करना",
"Several": "कई",
"Shake": "हिलाना",
"Share": "साझा करना",
"Sharp": "तेज",
"Sheet": "चादर",
"Ship": "जहाज",
"Shoot": "गोली मारना",
"Short": "छोटा",
"Should": "चाहिए",
"Show": "दिखाना",
"Side": "पक्ष",
"Sight": "दृष्टि",
"Sign": "चिह्न",
"Significant": "महत्वपूर्ण",
"Similar": "समान",
"Simple": "सरल",
"Since": "चूंकि",
"Single": "एकल",
"Situation": "स्थिति",
"Size": "आकार",
"Skill": "कौशल",
"Skin": "त्वचा",
"Small": "छोटा",
"Social": "सामाजिक",
"Solution": "समाधान",
"Some": "कुछ",
"Someone": "कोई",
"Something": "कुछ",
"Sometimes": "कभी कभी",
"Son": "बेटा",
"Song": "गीत",
"Soon": "जल्द ही",
"Sort": "प्रकार",
"Sound": "आवाज",
"Source": "स्रोत",
"Space": "अंतरिक्ष",
"Speak": "बोलना",
"Special": "विशेष",
"Specific": "विशिष्ट",
"Speech": "भाषण",
"Spend": "खर्च करना",
"Sport": "खेल",
"Staff": "कर्मचारी",
"Stage": "चरण",
"Stand": "खड़ा होना",
"Standard": "मानक",
"Start": "शुरू करना",
"State": "राज्य",
"Statement": "कथन",
"Station": "स्टेशन",
"Status": "स्थिति",
"Stay": "रहना",
"Step": "कदम",
"Still": "अभी तक",
"Stock": "स्टॉक",
"Stop": "रोकना",
"Store": "भंडार",
"Story": "कहानी",
"Straight": "सीधा",
"Strategy": "रणनीति",
"Street": "सड़क",
"Strong": "मजबूत",
"Structure": "संरचना",
"Student": "छात्र",
"Study": "अध्ययन",
"Stuff": "सामान",
"Style": "शैली",
"Subject": "विषय",
"Submit": "जमा करना",
"Subsequent": "बाद का",
"Substance": "पदार्थ",
"Success": "सफलता",
"Such": "ऐसा",
"Sudden": "अचानक",
"Suggest": "सुझाव देना",
"Summer": "गर्मी",
"Supply": "आपूर्ति",
"Support": "समर्थन",
"Suppose": "मानना",
"Sure": "निश्चित",
"Surface": "सतह",
"System": "प्रणाली",
"Table": "तालिका",
"Take": "लेना",
"Talk": "बात करना",
"Task": "कार्य",
"Tax": "कर",
"Teach": "सिखाना",
"Team": "टीम",
"Technical": "तकनीकी",
"Technique": "तकनीक",
"Technology": "प्रौद्योगिकी",
"Telephone": "टेलीफोन",
"Television": "टेलीविजन",
"Tell": "बताना",
"Temperature": "तापमान",
"Ten": "दस",
"Tend": "प्रवृत्त होना",
"Term": "शब्द",
"Test": "परीक्षण",
"Than": "से",
"Thank": "धन्यवाद",
"That": "वह",
"Their": "उनका",
"Them": "उन्हें",
"Then": "फिर",
"Theory": "सिद्धांत",
"There": "वहां",
"These": "ये",
"They": "वे",
"Thing": "चीज",
"Think": "सोचना",
"Third": "तीसरा",
"This": "यह",
"Those": "वे",
"Though": "हालांकि",
"Thought": "विचार",
"Thousand": "हजार",
"Threat": "खतरा",
"Through": "के माध्यम से",
"Throughout": "भर में",
"Thus": "इस प्रकार",
"Time": "समय",
"Today": "आज",
"Together": "एक साथ",
"Tomorrow": "कल",
"Tone": "स्वर",
"Tonight": "आज रात",
"Too": "भी",
"Tool": "उपकरण",
"Top": "शीर्ष",
"Total": "कुल",
"Touch": "स्पर्श करना",
"Toward": "की ओर",
"Town": "शहर",
"Trade": "व्यापार",
"Traditional": "पारंपरिक",
"Train": "ट्रेन",
"Travel": "यात्रा",
"Treat": "व्यवहार करना",
"Treatment": "उपचार",
"Tree": "पेड़",
"Trial": "परीक्षण",
"Trip": "यात्रा",
"Trouble": "परेशानी",
"True": "सत्य",
"Trust": "विश्वास",
"Truth": "सच्चाई",
"Try": "कोशिश करना",
"Turn": "मोड़ना",
"Twice": "दो बार",
"Type": "प्रकार",
"Typical": "विशिष्ट",
"Under": "के तहत",
"Understand": "समझना",
"Unit": "इकाई",
"Until": "जब तक",
"Upon": "पर",
"Upper": "ऊपरी",
"Use": "उपयोग करना",
"Useful": "उपयोगी",
"User": "उपयोगकर्ता",
"Usually": "आमतौर पर",
"Value": "मूल्य",
"Variable": "परिवर्तनीय",
"Various": "विभिन्न",
"Very": "बहुत",
"Video": "वीडियो",
"View": "दृश्य",
"Village": "गांव",
"Visit": "भ्रमण करना",
"Voice": "आवाज",
"Volume": "मात्रा",
"Vote": "मतदान करना",
"Wait": "इंतजार करना",
"Walk": "चलना",
"Wall": "दीवार",
"Want": "चाहना",
"War": "युद्ध",
"Watch": "देखना",
"Water": "पानी",
"Way": "तरीका",
"Weapon": "हथियार",
"Wear": "पहनना",
"Week": "सप्ताह",
"Weight": "वजन",
"Well": "अच्छी तरह से",
"West": "पश्चिम",
"What": "क्या",
"Whatever": "जो कुछ भी",
"When": "कब",
"Where": "कहाँ",
"Whether": "चाहे",
"Which": "कौन सा",
"While": "जबकि",
"White": "सफेद",
"Who": "कौन",
"Whole": "पूरा",
"Whose": "किसका",
"Why": "क्यों",
"Wide": "चौड़ा",
"Will": "होगा",
"Win": "जीतना",
"Wind": "हवा",
"Window": "खिड़की",
"Wish": "इच्छा",
"With": "के साथ",
"Within": "के भीतर",
"Without": "के बिना",
"Woman": "महिला",
"Wonder": "आश्चर्य",
"Word": "शब्द",
"Work": "काम",
"Worker": "कर्मचारी",
"World": "दुनिया",
"Worry": "चिंता करना",
"Write": "लिखना",
"Wrong": "गलत",
"Yard": "आंगन",
"Yeah": "हाँ",
"Year": "वर्ष",
"Yellow": "पीला",
"Yes": "हाँ",
"Yesterday": "कल",
"Yet": "अभी तक",
"Yield": "उपज",
"Young": "युवा",
"Your": "तुम्हारा",
"Yours": "तुम्हारा",
"Yourself": "स्वयं",
"Youth": "युवा",
"Zone": "क्षेत्र",
"Zoo": "चिड़ियाघर",
"Abandon": "त्यागना",
"Abbreviate": "संक्षिप्त करना",
"Ability": "क्षमता",
"Abnormal": "असामान्य",
"Abolish": "समाप्त करना",
"Abrupt": "अचानक",
"Absorb": "सोखना",
"Abstract": "अमूर्त",
"Abundance": "प्रचुरता",
"Abuse": "दुरुपयोग",
"Academic": "शैक्षणिक",
"Accelerate": "तेज करना",
"Access": "पहुंच",
"Accompany": "साथ देना",
"Accomplish": "पूरा करना",
"Accord": "समझौता",
"Account": "लेखा",
"Accumulate": "जमा करना",
"Accurate": "सटीक",
"Accuse": "आरोप लगाना",
"Achieve": "प्राप्त करना",
"Acknowledge": "स्वीकार करना",
"Acquire": "अर्जित करना",
"Activate": "सक्रिय करना",
"Adapt": "अनुकूल बनाना",
"Adequate": "पर्याप्त",
"Adhere": "पालन करना",
"Adjacent": "निकटवर्ती",
"Adjust": "समायोजित करना",
"Administer": "प्रशासन करना",
"Admire": "प्रशंसा करना",
"Admit": "मानना",
"Adopt": "अपनाना",
"Advance": "आगे बढ़ना",
"Advantage": "लाभ",
"Adverse": "विपरीत",
"Advise": "सलाह देना",
"Advocate": "समर्थन करना",
"Affair": "मामला",
"Affect": "प्रभावित करना",
"Affiliate": "संबद्ध करना",
"Affirm": "पुष्टि करना",
"Afflict": "कष्ट देना",
"Afford": "सामर्थ्य रखना",
"Agenda": "कार्यसूची",
"Aggregate": "कुल",
"Aggressive": "आक्रामक",
"Agitate": "आंदोलित करना",
"Agree": "सहमत होना",
"Aid": "सहायता",
"Aim": "लक्ष्य",
"Alarm": "अलार्म",
"Alert": "सतर्क",
"Alienate": "अलग करना",
"Align": "संरेखित करना",
"Allege": "आरोप लगाना",
"Allocate": "आवंटित करना",
"Allow": "अनुमति देना",
"Alter": "बदलना",
"Alternate": "वैकल्पिक",
"Amass": "इकट्ठा करना",
"Ambiguous": "अस्पष्ट",
"Amend": "संशोधन करना",
"Amplify": "बढ़ाना",
"Analyze": "विश्लेषण करना",
"Animate": "सजीव करना",
"Announce": "घोषणा करना",
"Annotate": "टिप्पणी करना",
"Annual": "वार्षिक",
"Anticipate": "पूर्वानुमान करना",
"Apart": "अलग",
"Apparent": "स्पष्ट",
"Appeal": "अपील",
"Appear": "दिखाई देना",
"Appease": "शांत करना",
"Append": "जोड़ना",
"Applaud": "वाहवाही करना",
"Apply": "आवेदन करना",
"Appoint": "नियुक्त करना",
"Appraise": "मूल्यांकन करना",
"Appreciate": "सराहना करना",
"Apprehend": "गिरफ्तार करना",
"Approach": "दृष्टिकोण",
"Appropriate": "उचित",
"Approve": "मंजूर करना",
"Approximate": "लगभग",
"Argue": "तर्क करना",
"Arise": "उठना",
"Arrange": "व्यवस्थित करना",
"Arrest": "गिरफ्तार करना",
"Arrive": "पहुंचना",
"Ascend": "चढ़ना",
"Ascertain": "पता लगाना",
"Ascribe": "श्रेय देना",
"Assemble": "इकट्ठा करना",
"Assert": "जोर देना",
"Assess": "आकलन करना",
"Assign": "सौंपना",
"Assist": "सहायता करना",
"Associate": "सहयोगी",
"Assume": "मान लेना",
"Assure": "आश्वस्त करना",
"Astonish": "चकित करना",
"Attach": "जोड़ना",
"Attack": "हमला करना",
"Attain": "प्राप्त करना",
"Attempt": "प्रयास करना",
"Attend": "उपस्थित होना",
"Attest": "साक्षी देना",
"Attract": "आकर्षित करना",
"Attribute": "गुण",
"Audit": "लेखा परीक्षा"

}

a = input("ENTER WORD TO TRANSLATE: ")
if a.title() in dict:
    print(a.title(),": ",dict[a.title()])
else:
    print("Word not found in dictionary")